fix: undefined voteBalance
unik-name/uns-core pull request #330
Opened 2021-08-05 10:07 UTC by peterjah

2021-08-05 14:06 UTC, dlecan requested changes
1️⃣`@unikname` 👉 `UniknameID`
:two: `vote` 👉 `support`

:three: I'm surprised because most of the new code is not covered by the new tests: Codecov failure or missing tests?

2021-08-05 14:06 UTC, dlecan commented on plugins/uns/uns-transactions/src/errors.ts
> +        super(`Failed to apply transaction because the Unikname "${tokenId}" is not disclosed`);
```suggestion
        super(`Failed to apply transaction because the UniknameID "${tokenId}" is not disclosed`);
```

2021-08-05 14:06 UTC, dlecan commented on plugins/uns/uns-transactions/src/errors.ts
> +        super(`Failed to register Unikname as delegate: Unikname of type "${type}" is not allowed`);
```suggestion
        super(`Failed to register a UniknameID as a delegate: a UniknameID of type "${type}" is not allowed`);
```

2021-08-05 14:06 UTC, dlecan commented on plugins/uns/uns-transactions/src/errors.ts
> +        super(`Failed to register Unikname as delegate: crypto-account has already a delegate Unikname`);
```suggestion
        super(`Failed to register a UniknameID as a delegate: the crypto-account already owns at least one UniknameID as a delegate `);
```

2021-08-05 14:06 UTC, dlecan commented on plugins/uns/uns-transactions/src/errors.ts
> +        super(`Failed to apply transaction: crypto-account has no delegate Unikname`);
```suggestion
        super(`Failed to apply transaction: the crypto-account hasn't any UniknameID as a delegate`);
```

2021-08-05 14:06 UTC, dlecan commented on plugins/uns/uns-transactions/src/errors.ts
> +        super(`Failed to apply transaction: crypto-account has several Uniknames`);
```suggestion
        super(`Failed to apply transaction: the crypto-account has several UniknameID`);
```

2021-08-05 14:06 UTC, dlecan commented on plugins/uns/uns-transactions/src/errors.ts
> +        super(`Failed to apply transaction ${transactionId}: crypto-account has no Unikname`);
```suggestion
        super(`Failed to apply transaction ${transactionId}: the crypto-account has no UniknameID`);
```

2021-08-05 14:06 UTC, dlecan commented on plugins/uns/uns-transactions/src/errors.ts
> +            `Failed to apply vote transaction ${transactionId}: voter Unikname type must be the same as delegate Unikname type`,
```suggestion
            `Failed to apply vote transaction ${transactionId}: the type of the UniknameID supporter (voter) must be the same type as the one of the delegate`,
```

2021-08-05 14:06 UTC, dlecan commented on plugins/uns/uns-transactions/src/errors.ts
> +            ).toLowerCase()} Unikname because wallet is voting for ${DIDHelpers.fromCode(
```suggestion
            ).toLowerCase()} UniknameID because the crypto-account is already supporting (voting for) ${DIDHelpers.fromCode(
```

2021-08-05 14:06 UTC, dlecan commented on plugins/uns/uns-transactions/src/errors.ts
> +            ).toLowerCase()} delegate. Please unvote first`,
```suggestion
            ).toLowerCase()} delegate. Please remove your support (unvote) first`,
```

2021-08-05 14:06 UTC, dlecan commented on plugins/uns/uns-transactions/src/handlers/uns-certified-nft-mint.ts
> +            // check type of delegate voted with a previously owned token
```suggestion
            // check type of delegate's vote with a previously owned token
```

2021-08-05 16:09 UTC, peterjah commented
>  I'm surprised because most of the new code is not covered by the new tests: Codecov failure or missing tests?

what new code are you speaking ?? 
i did not write new test to cover the fix of voteBalance
the new feature "check delegate type when mint" is tested

2021-08-06 08:30 UTC, dlecan approved these changes

2021-08-06 10:07 UTC, merged